<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c3e5c205-65b8-48bb-baae-c94761349a39</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.1" />
    <PackageReference Include="Aspire.Hosting.MySql" Version="9.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RealEstateAgencyApp.Api\RealEstateAgencyApp.Api.csproj" />
    <ProjectReference Include="..\RealEstateAgencyApp.Grp\RealEstateAgencyApp.Grp.csproj" />
  </ItemGroup>

</Project>
