name: .NET Tests

on:
  push:
    branches: [ main, lab_1 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test ./RealEstateAgencyApp.Tests/RealEstateAgencyApp.Tests.csproj --no-build --verbosity normal --configuration Release